name: 'Susan Morduch, PhD'
markdown: redcarpet
imageurl: /media
permalink: /:title
baseurl: ''

prose:
  media: 'media'
  ignore:
    - /CNAME
    - /.gitignore
    - /Gemfile
    - /Gemfile.lock
    - /README.md
    - /robots.txt
    - /static
    - /_layouts
    - /_includes/html
    - /_data
    - /_config.yml
  metadata:
    _posts:
      - name: 'layout'
        field:
          element: 'select'
          label: 'Page Layout'
          value: 'default'
          help: 'Sidebar layout requires a sibebar file in the folder _includes. File name must be page-url_sidebar.md'
          options:
          - name: 'Single Column'
            value: 'default'
          - name: 'Two Column (sidebar)'
            value: 'sidebar'
      - name: 'title'
        field:
          element: 'text'
          label: 'Page Title'
          type: 'text'
      # - name: 'header_image'
      #   field:
      #     element: 'text'
      #     label: 'Header Image'
      #     help: 'Name of file (e.g. image.jpg), must be uploaded media'
      #     type: 'text'
